// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddBookInput struct {
	Title  string `json:"title"`
	Author string `json:"author"`
}

type Book struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	Author string `json:"author"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginPayload struct {
	Token string `json:"token"`
}

type Mutation struct {
}

type Query struct {
}
