package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"

	"github.com/wricardo/gqlcli/example/graph/model"
)

// Author is the resolver for the author field.
func (r *bookResolver) Author(ctx context.Context, obj *model.Book) (*model.Author, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	for _, a := range r.authors {
		if a.ID == obj.Author.ID {
			return a, nil
		}
	}
	return obj.Author, nil
}

// AddBook is the resolver for the addBook field.
func (r *mutationResolver) AddBook(ctx context.Context, input model.AddBookInput) (*model.Book, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	author := r.getOrCreateAuthor(input.AuthorName)
	book := &model.Book{
		ID:     fmt.Sprintf("%d", r.nextID),
		Title:  input.Title,
		Author: author,
	}
	r.nextID++
	r.books = append(r.books, book)
	r.save()
	return book, nil
}

// Books is the resolver for the books field.
func (r *queryResolver) Books(ctx context.Context) ([]*model.Book, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	result := make([]*model.Book, len(r.books))
	copy(result, r.books)
	return result, nil
}

// Book is the resolver for the book field.
func (r *queryResolver) Book(ctx context.Context, id string) (*model.Book, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	for _, b := range r.books {
		if b.ID == id {
			return b, nil
		}
	}
	return nil, nil
}

// Book returns BookResolver implementation.
func (r *Resolver) Book() BookResolver { return &bookResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type bookResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
