package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"

	"github.com/wricardo/gqlcli/example/graph/model"
)

// AddBook is the resolver for the addBook field.
func (r *mutationResolver) AddBook(ctx context.Context, input model.AddBookInput) (*model.Book, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	book := &model.Book{
		ID:     fmt.Sprintf("%d", r.nextID),
		Title:  input.Title,
		Author: input.Author,
	}
	r.nextID++
	r.books = append(r.books, book)
	return book, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginPayload, error) {
	// Hardcoded credentials for the example — replace with real auth in production.
	if input.Email == "admin@example.com" && input.Password == "secret" {
		return &model.LoginPayload{
			Token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20ifQ.example",
		}, nil
	}
	return nil, fmt.Errorf("invalid credentials")
}

// Books is the resolver for the books field.
func (r *queryResolver) Books(ctx context.Context) ([]*model.Book, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	result := make([]*model.Book, len(r.books))
	copy(result, r.books)
	return result, nil
}

// Book is the resolver for the book field.
func (r *queryResolver) Book(ctx context.Context, id string) (*model.Book, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	for _, b := range r.books {
		if b.ID == id {
			return b, nil
		}
	}
	return nil, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
